### ISSUE TITLE
when download  dataset，error

### ISSUE THREAD

**Issue by GloriaZLQ** [cxhernandez/cellcount#10]
```python-traceback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tensorflow\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\tensorflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zhang\Desktop\cellcount-master\cellcount-master\cellcount\cli\main.py", line 53, in <module>
    main()
  File "C:\Users\zhang\Desktop\cellcount-master\cellcount-master\cellcount\cli\main.py", line 34, in main
    args_func(args, p)
  File "C:\Users\zhang\Desktop\cellcount-master\cellcount-master\cellcount\cli\main.py", line 39, in args_func
    args.func(args, p)
  File "C:\Users\zhang\Desktop\cellcount-master\cellcount-master\cellcount\cli\parser_download.py", line 88, in func
    dl_unzip(image_uri, outdir, update)
  File "C:\Users\zhang\Desktop\cellcount-master\cellcount-master\cellcount\cli\parser_download.py", line 58, in dl_unzip
    reporthook=reporthook)
  File "C:\Anaconda3\envs\tensorflow\lib\urllib\request.py", line 198, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ZHANG~1\\AppData\\Local\\Temp\\tmp6qzt4v45'
```

**Comment by cxhernandez** [comment]
As the error states, there seems to be an issue with write-access permissions in your temporary files directory when using `urllib.request.urlretrieve`.

Since this isn't necessarily an issue with the `cellcount` package and I have relatively little experience with Windows, I'd defer to searching StackOverflow for a solution.
