### ISSUE TITLE
"No module named request"

### ISSUE THREAD

**Issue by dstrib** [cxhernandez/cellcount#11]
I believe I have all requested dependencies, but get this error:
Traceback (most recent call last):
  File "/home/ds/programs/python_packages/bin/cellcount", line 11, in <module>
    load_entry_point('cellcount==0.1a0', 'console_scripts', 'cellcount')()
  File "build/bdist.linux-x86_64/egg/cellcount/cli/main.py", line 33, in main
  File "build/bdist.linux-x86_64/egg/cellcount/cli/main.py", line 38, in args_func
  File "build/bdist.linux-x86_64/egg/cellcount/cli/parser_download.py", line 17, in func
ImportError: No module named request

**Comment by cxhernandez** [comment]
Are you using Python 2 by any chance?

**Comment by dstrib** [comment]
I am! Is this written in python3? I didn't see that in the docs.
